
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABD-D-PC8
 */
public class jfrmSupport extends javax.swing.JFrame {

    /**
     * Creates new form jfrmSupport
     */
    public jfrmSupport() {
        initComponents();
        this.setSize(1000, 600);
        this.setTitle("Mother_Board");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblPiezas = new javax.swing.JLabel();
        jlblFunction = new javax.swing.JLabel();
        jlblNomPieza = new javax.swing.JLabel();
        jlblConcepto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(83, 115, 221));

        jlblPiezas.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jlblPiezas.setText("Nombre");

        jlblFunction.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jlblFunction.setText("Función principal:");

        jlblNomPieza.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jlblNomPieza.setText("Imagen");

        jlblConcepto.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jlblConcepto.setText("Concepto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jlblPiezas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblConcepto)
                            .addComponent(jlblFunction))))
                .addContainerGap(705, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jlblNomPieza)
                    .addContainerGap(374, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlblPiezas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addComponent(jlblConcepto)
                .addGap(18, 18, 18)
                .addComponent(jlblFunction)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jlblNomPieza)
                    .addContainerGap(452, Short.MAX_VALUE)))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Imagenes");

        jMenuItem4.setText("Motherboard");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("RAM");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Fuente de Poder");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem9.setText("Acerca del Programa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Créditos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jlblPiezas.setText("");
        jlblPiezas.setText("Procesador");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cpu.png")));
        jlblNomPieza.setText("");
        jlblConcepto.setText("El procesador (Unidad Central de Procesamiento) es el cerebro del computador, compuesto por millones de transistores que ejecutan operaciones lógicas y matemáticas.");
        jlblFunction.setText("Interpretar y ejecutar las instrucciones de los programas y del sistema operativo, procesando los datos de entrada para devolver resultados específicos.");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jlblPiezas.setText("");
        jlblPiezas.setText("RAM");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ram.png")));
        jlblNomPieza.setText("");
        jlblConcepto.setText("La RAM (Memoria de Acceso Aleatorio) es un tipo de memoria volátil y ultrarrápida que almacena de forma temporal los datos de los programas activos.");
        jlblFunction.setText("Proporcionar un espacio de trabajo inmediato al procesador para que este pueda acceder a las instrucciones y datos de las aplicaciones en ejecución de manera casi instantánea.");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jlblPiezas.setText("");
        jlblPiezas.setText("Motherboard");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/motherboard.png")));
        jlblNomPieza.setText("");
        jlblConcepto.setText("La motherboard o placa base es la tarjeta de circuito impreso principal del computador, a la que se conectan todos los demás componentes y periféricos.");
        jlblFunction.setText("Actuar como la plataforma de comunicación central, permitiendo que el procesador, la memoria, el almacenamiento y las tarjetas de expansión interactúen entre sí de forma estable y coordinada.");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jlblPiezas.setText("");
        jlblPiezas.setText("Cooler");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cooler.png")));
        jlblNomPieza.setText("");
        jlblConcepto.setText("El cooler o disipador del procesador es un sistema de enfriamiento térmico (por aire o líquido) diseñado específicamente para controlar la temperatura del chip de la CPU.");
        jlblFunction.setText("Transferir el calor generado por el procesador hacia un disipador de aluminio o cobre y luego evacuarlo con un ventilador, evitando que la CPU sufra daños por sobrecalentamiento o aplique 'thermal throttling'.");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jlblPiezas.setText("");
        jlblPiezas.setText("Fuente de Poder");
        jlblNomPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fuente.png")));
        jlblNomPieza.setText("");
        jlblConcepto.setText("La fuente de poder es el componente encargado de transformar la corriente alterna (AC) de la red eléctrica en corriente continua (DC) apta para el PC.");
        jlblFunction.setText("Suministrar la energía eléctrica con los voltajes adecuados (3.3V, 5V, 12V) y de forma estable a todos los componentes de la computadora.");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int msg = JOptionPane.showConfirmDialog(this, "¿Desea salir del softare? 😁");
        if (msg == 0)
            System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        String acercaDe = "Componentes de PC - Catálogo Interactivo\n\n"
                + "Esta aplicación didáctica permite explorar y conocer a detalle\n"
                + "los componentes esenciales de hardware de una computadora,\n"
                + "mostrando su concepto, imagen y función principal.";

        JOptionPane.showMessageDialog(null, acercaDe, "Acerca del Programa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        String creditos = "CRÉDITOS DEL PROYECTO\n\n"
                + "Desarrollador:\n"
                + "Juan Ignacio Arévalo Toc\n\n"
                + "Grado y Carrera:\n"
                + "IV Bachillerato en Ciencias y Letras con Orientación en Computación\n\n"
                + "Sección: \"C\"\n"
                + "Clave: 3\n\n"
                + "¡Gracias por utilizar la aplicación!";

        JOptionPane.showMessageDialog(null, creditos, "Créditos del Sistema", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmSupport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblConcepto;
    private javax.swing.JLabel jlblFunction;
    private javax.swing.JLabel jlblNomPieza;
    private javax.swing.JLabel jlblPiezas;
    // End of variables declaration//GEN-END:variables
}
